### ISSUE TITLE
I added some other statuses, would you merge them?

### ISSUE THREAD

**Issue by TrontheTechie** [SirArchLinux/runelite-polybar-integration#1]
I was messing around with the plugin and kinda sad that other things weren't represented aside from woodcutting, so I added most others. Would you be willing to merge the changes to your plugin, or are you working on some of this yourself already?

Repo is here:  https://github.com/TrontheTechie/runelite-polybar-integration

**Comment by SirArchLinux** [comment]
Sure, nice work. I will look into it!
Did you group the AnimationID's all by yourself or have you found a very good source for that (e.g from the idle notifier plugin)?

Anyways, thanks for showing interest in my project. If you want to get in contact with me, you can add me on Discord (**SirArchLinux#4988**). Also check out the official [RuneLite Discord channel](https://runelite.net/discord) :)

**Comment by TrontheTechie** [comment]
I just added the animationID's to the existing switch, some were not named in AnimationID's so were added by hand as integers. Idle notifier would be a good place to look, as well as XP tracking for future additions/ more accurate output.
